name: Forge CI

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and install dependencies
        uses: ./.github/actions/test
        with:
          path: ${{ inputs.app-path }}

      - name: Run tests
        shell: bash
        working-directory: ${{ inputs.app-path }}
        run: npm test
