name: Forge CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and install dependencies
        uses: ./.github/actions/test

      - name: Run tests
        shell: bash
        run: npm test
